apiVersion: v1
appVersion: "1.0"
description: Fineract Engine
name: fin-engine
version: 1.0.0-SNAPSHOT
dependencies:
- name: mariadb
  version: 10.5.16
  repository: "https://charts.bitnami.com/bitnami"
  alias: mysql

