namespace: "default"
fineract:
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "bb"
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/fineract"
  ingress:
    enabled: true
    hostname: "fynams.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"  
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    path: "/"
    backend:
      service:
        name: fineractserver
        port:
          number: 8443
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi"

communityapp:
  enabled: true
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/community-app"
  ingress:
    enabled: true
    hostname: "communityapp.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"
    path: "/?baseApiUrl=https://fynams.sandbox.fynarfin.io/"
    backend:
      service:
        name: mifoscommunity
        port:
          number: 9090
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi"

webapp:
  image: "us.icr.io/phee-ns/web-app:latest"
  ingress:
    enabled: false
    hostname: ""
    path: "/web"
    annotations:
      kubernetes.io/ingress.class: "nginx"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi" 

selfservice:
  image: "us.icr.io/phee-ns/web-self-service-app:latest"
  ingress:
    enabled: false
    hostname: ""
    path: "/self"
    annotations: {}




mysql:
  image:
    tag: "10.5.15-debian-10-r0"
    debug: true
  auth:
    username: "mifos"
    password: "password"
    rootPassword: "4ET6ywqlGt"
  initdbScripts:
    setup.sql: |-
      # create databases
      CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
      CREATE DATABASE IF NOT EXISTS `fineract_default`;
      # create root user and grant rights
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
      GRANT ALL PRIVILEGES ON `fineract_default`.* TO 'mifos';
  primary:
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

wildcardhostname: "*.fynarfin.io"

tls: ""  
