communityapp:
  enabled: true
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/community-app:latest"
  ingress:
    enabled: true
    hostname: "communityapp.sandbox.fynarfin.io"
    path: "/"
    wildcardhostname: "communityapp.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi"

wildcardhostname: "*.sandbox.fynarfin.io"

tls: ""       