version: 2.1

jobs:
  build-and-deploy:
    docker:
    - image: cimg/base:stable

    steps:
    - checkout

    # Install AWS CLI
    - run:
        name: Install AWS CLI
        command: |
          sudo apt-get update && sudo apt-get install -y awscli

    # Install kubectl
    - run:
        name: Install kubectl
        command: |
          sudo apt-get install -y apt-transport-https
          sudo curl -s -o /usr/local/bin/kubectl "https://amazon-eks.s3.us-west-2.amazonaws.com/1.23.7/2022-01-21/bin/linux/amd64/kubectl"
          sudo chmod +x /usr/local/bin/kubectl

    # Configure AWS credentials
    - run:
        name: Configure AWS credentials
        command: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $REGION

    # Authenticate with EKS cluster
    - run:
        name: Authenticate with EKS cluster
        command: aws eks update-kubeconfig --name sit

    # Build and deploy Helm chart
    - run:
        name: Build and deploy Helm chart
        command: |
          cd helm/fineract/values.yaml
          helm dependency update
          helm upgrade --install fineract --create-namespace --namespace fineract

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build-and-deploy:
        contexts:
        - aws


