version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Configure AWS Credentials
          command: aws configure set aws_access_key_id $AWS_ACCESS_KEY && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $REGION
      - run:
          name: Install kubectl
          command: |
            sudo curl --silent --location -o /usr/local/bin/kubectl "https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl"
            sudo chmod +x /usr/local/bin/kubectl
      - run:
          name: Authenticate kubectl with EKS Cluster
          command: aws eks --region $REGION update-kubeconfig --name sit
      

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - helm/install-helm-client:
          version: "v3.8.2"
      - run:
          name: Deploy Helm Chart
          command: |
            helm upgrade --install helm/fineract/values.yaml fineract helm/fineract/ --create-namespace --namespace fineract

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
