{{- if .Values.selfservice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service
  labels:
    app: self-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-service
  template:
    metadata:
      labels:
        app: self-service
    spec:
      containers:
      - image: "{{ .Values.selfservice.image }}"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "0.5Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 1                      
        imagePullPolicy: Always
        name: self-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
#      serviceAccountName: ""
#      volumes: null
{{- end }}
